In [1]:
import pandas as pd
df = pd.read_csv(
 'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

/var/folders/pd/q9m5ptyn78118znr2yc_jql40000gn/T/ipykernel_10065/572529936.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [2]:
df.head()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

In [3]:
# Question 1

df['code_commune'] = (
    df['code_departement'].astype(str) +
    df['code_commune'].astype(str).str.zfill(3)
    )

df['candidat'] = ( df['nom'] +' '+ df['prenom'])

df.head()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,ARTHAUD Nathalie
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,ARTHAUD Nathalie
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,ARTHAUD Nathalie
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,ARTHAUD Nathalie
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,ARTHAUD Nathalie

In [4]:
# Question 2
df['candidat'].value_counts()

candidats = df['candidat'].nunique()

print( f"En 2022, il y avait {candidats} candidats à l'élection présidentielle.")

En 2022, il y avait 12 candidats à l'élection présidentielle.

In [5]:
# Question 3

# QUESTION 4

In [ ]:
df_votes = df[~df["candidat"].isin(["Abstentions", "Blancs", "Nuls"])].copy()

score_departements = (
    df_votes
    .groupby(["code_departement", "candidat"], as_index=False)["voix"]
    .sum()
    .rename(columns={"voix": "votes"})
)

totaux_departement = (
    score_departements
    .groupby("code_departement", as_index=False)["votes"]
    .sum()
    .rename(columns={"votes": "total_votes_departement"})
)

score_departements = score_departements.merge(totaux_departement, on="code_departement")
score_departements["score"] = (
    score_departements["votes"] / score_departements["total_votes_departement"] * 100
).round(2)

score_departements = score_departements.sort_values(
    by=["code_departement", "votes"],
    ascending=[True, False]
).reset_index(drop=True)

score_departements.describe

<bound method NDFrame.describe of      code_departement               candidat  votes  total_votes_departement  \
0                  01        MACRON Emmanuel  92206                   333024
1                  01          LE PEN Marine  86755                   333024
2                  01     MÉLENCHON Jean-Luc  57832                   333024
3                  01           ZEMMOUR Éric  27530                   333024
4                  01       PÉCRESSE Valérie  17572                   333024
...               ...                    ...    ...                      ...
1291      fr_etranger  DUPONT-AIGNAN Nicolas   7074                   498951
1292      fr_etranger          LASSALLE Jean   5964                   498951
1293      fr_etranger         ROUSSEL Fabien   3266                   498951
1294      fr_etranger        POUTOU Philippe   3145                   498951
1295      fr_etranger       ARTHAUD Nathalie   1300                   498951

      score
0     27.69
1     26.05
2     17.37
3      8.27
4      5.28
...     ...
1291   1.42
1292   1.20
1293   0.65
1294   0.63
1295   0.26

[1296 rows x 5 columns]>